export const INCREMENT_START = "INCREMENT_START";
export const DECREMENT_START = "DECREMENT_START";
export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";
